DIGI_10_createAddOn
RAMUNIMMALA/digiorder_enterprise pull request #13
Opened 2020-07-22 15:17 UTC by bommavikas

1)Created AddOnController for Create AddOn
2)Created AddOnLibrary
3)Created View for Create AddOn
4)Created AddOnModel
5)Modified LibraryUtility

2020-08-11 11:45 UTC, anebhargavkrishna commented on DigiOrderEnterprise/DigiOrderEnterprise/Web.config
> -    <add key="digiapigrant_type" value="password"/>
add password to config file

2020-08-11 11:47 UTC, anebhargavkrishna commented on DigiOrderEnterprise/DigiOrderEnterpriseLibrary/DigiOrderEnterpriseLibrary.csproj
> -    </Reference>
add these reference

2020-08-11 11:47 UTC, anebhargavkrishna commented on DigiOrderEnterprise/DigiOrderEnterpriseLibrary/DigiOrderEnterpriseLibrary.csproj
> -    <None Include="packages.config" />
Why you removed taxpagelibrary

2020-08-11 14:21 UTC, bommavikas commented on DigiOrderEnterprise/DigiOrderEnterprise/Web.config
> -    <add key="digiapigrant_type" value="password"/>
added

2020-08-12 06:40 UTC, anebhargavkrishna commented on DigiOrderEnterprise/DigiOrderEnterprise/DigiOrderEnterprise.csproj
> +  <Reference Include="DigiOrderEnterpriseLibrary, Version=1.0.0.0, Culture=neutral, processorArchitecture=MSIL">
Add space before reference

2020-08-12 06:40 UTC, anebhargavkrishna commented on DigiOrderEnterprise/DigiOrderEnterprise/Web.config
> +	  <add key="digiapiurl" value="http://localhost:52893/api/" />
Remove port address

2020-08-12 06:41 UTC, anebhargavkrishna commented on DigiOrderEnterprise/DigiOrderEnterpriseLibrary/DigiOrderEnterpriseLibrary.csproj
> +    <Compile Include="obj\Debug\TemporaryGeneratedFile_E7A71F73-0F8D-4B9B-B56E-8E70B10BC5D3.cs" />
Remove these debug file

2020-08-12 06:41 UTC, anebhargavkrishna commented on DigiOrderEnterprise/DigiOrderEnterpriseLibrary/DigiOrderEnterpriseLibrary.csproj
> +    <None Include="obj\Debug\DigiOrderEnterpriseLibrary.csprojAssemblyReference.cache" />
Remove these debug files

2020-08-12 06:41 UTC, anebhargavkrishna commented on DigiOrderEnterprise/DigiOrderEnterpriseLibrary/DigiOrderEnterpriseLibrary.csproj
> +  </ItemGroup>
Remove these debug files

2020-08-12 07:04 UTC, bommavikas commented on DigiOrderEnterprise/DigiOrderEnterpriseLibrary/DigiOrderEnterpriseLibrary.csproj
> -    <None Include="packages.config" />
Included TaxPageLibrary

2020-08-12 07:04 UTC, bommavikas commented on DigiOrderEnterprise/DigiOrderEnterprise/Controllers/AddOnController.cs
> +        // GET: MenuItem
REMOVED

2020-08-12 07:06 UTC, bommavikas commented on DigiOrderEnterprise/DigiOrderEnterprise/Controllers/AddOnController.cs
> +        /// Reviewer:
Added

2020-08-12 07:09 UTC, bommavikas commented on DigiOrderEnterprise/DigiOrderEnterpriseLibrary/DigiOrderEnterpriseLibrary.csproj
> -    </Reference>
Added

2020-08-12 07:23 UTC, bommavikas commented on DigiOrderEnterprise/DigiOrderEnterprise/Controllers/AddOnController.cs
> +                ViewBag.ErrorMessage = "";
Added

2020-08-12 07:23 UTC, bommavikas commented on DigiOrderEnterprise/DigiOrderEnterprise/DigiOrderEnterprise.csproj
> +  <Reference Include="DigiOrderEnterpriseLibrary, Version=1.0.0.0, Culture=neutral, processorArchitecture=MSIL">
Added

2020-08-12 07:24 UTC, bommavikas commented on DigiOrderEnterprise/DigiOrderEnterpriseLibrary/DigiOrderEnterpriseLibrary.csproj
> +    <Compile Include="obj\Debug\TemporaryGeneratedFile_E7A71F73-0F8D-4B9B-B56E-8E70B10BC5D3.cs" />
Removed

2020-08-12 07:24 UTC, bommavikas commented on DigiOrderEnterprise/DigiOrderEnterpriseLibrary/DigiOrderEnterpriseLibrary.csproj
> +  </ItemGroup>
Removed

2020-08-12 09:09 UTC, anebhargavkrishna commented on DigiOrderEnterprise/DigiOrderEnterprise/DigiOrderEnterprise.csproj
> +    <Content Include="Web.config">
check  spaces in line 239 compare with removed one

2020-08-12 09:09 UTC, anebhargavkrishna commented on DigiOrderEnterprise/DigiOrderEnterprise/DigiOrderEnterprise.csproj
> +    </Content>
Remove these two lines

2020-08-12 11:50 UTC, bommavikas commented on DigiOrderEnterprise/DigiOrderEnterpriseLibrary/AddOnLibrary.cs
> +        {
Taken all Values In Model Object

2020-08-12 12:26 UTC, bommavikas commented on DigiOrderEnterprise/DigiOrderEnterprise/Web.config
> +	  <add key="digiapiurl" value="http://localhost:52893/api/" />
Removed Port Adreess And Replaced

2020-08-12 12:28 UTC, bommavikas commented on DigiOrderEnterprise/DigiOrderEnterpriseLibrary/DigiOrderEnterpriseLibrary.csproj
> +    <None Include="obj\Debug\DigiOrderEnterpriseLibrary.csprojAssemblyReference.cache" />
Removed Debug Files

2020-08-12 12:30 UTC, bommavikas commented on DigiOrderEnterprise/DigiOrderEnterprise/DigiOrderEnterprise.csproj
> +    </Content>
Removed Lines

2020-08-13 06:50 UTC, anebhargavkrishna commented on DigiOrderEnterprise/DigiOrderEnterprise/DigiOrderEnterprise.csproj
>      </Content>
Revert this file

2020-08-13 06:50 UTC, anebhargavkrishna commented on DigiOrderEnterprise/DigiOrderEnterpriseLibrary/DigiOrderEnterpriseLibrary.csproj
>      <None Include="packages.config" />
Revert this file

2020-08-13 06:50 UTC, anebhargavkrishna commented on DigiOrderEnterprise/DigiOrderEnterpriseModel/DigiOrderEnterpriseModel.csproj
>      <Compile Include="CategoryModel.cs" />
Revert this file

2020-08-13 06:51 UTC, anebhargavkrishna commented on DigiOrderEnterprise/DigiOrderEnterpriseModel/AddOnModel.cs
> +}
Revert this file as you have checkined in list addons pr

2020-08-18 11:22 UTC, bommavikas commented on DigiOrderEnterprise/DigiOrderEnterprise/DigiOrderEnterprise.csproj
>      </Content>
Reverted

2020-08-18 11:23 UTC, bommavikas commented on DigiOrderEnterprise/DigiOrderEnterpriseLibrary/DigiOrderEnterpriseLibrary.csproj
>      <None Include="packages.config" />
Reveretd

2020-08-18 11:23 UTC, bommavikas commented on DigiOrderEnterprise/DigiOrderEnterpriseModel/DigiOrderEnterpriseModel.csproj
>      <Compile Include="CategoryModel.cs" />
Reverted

2020-08-19 07:01 UTC, anebhargavkrishna requested changes

2020-08-19 07:01 UTC, anebhargavkrishna commented on DigiOrderEnterprise/DigiOrderEnterprise/DigiOrderEnterprise.csproj
> + <Content Include="Web.config" />
Remove this

2020-08-19 07:06 UTC, bommavikas commented on DigiOrderEnterprise/DigiOrderEnterprise/DigiOrderEnterprise.csproj
> + <Content Include="Web.config" />
Removed

2020-09-02 02:20 UTC, merged